#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${ENV_GITHUB_TOKEN}@github.com/joelibaceta/graphql-spanish-guide.git --branch gh-pages _site

bundle exec jekyll build --baseurl "graphql-spanish-guide/"

# push
cd _site
git config user.email ${ENV_USER_EMAIL}
git config user.name ${ENV_USER_NAME}
git add --all
git commit -a -m "Travis Build #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
